PROJ_NAME  :=  gnss_ins_dr_sync
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/gnss_ins_dr_sync

# compile config
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LINK_PRINTF_FLOAT:=y
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=O1
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/stm32/stm32f407_ebf_bth/make.mk

# os and library config
MK_COMPILER=gcc
MK_RTOS=none
MK_MEM_METHOD=4
MK_USE_POSIX=n
MK_USE_LIB_CPP=n

MK_USE_FS_FATFS=n
MK_USE_CRUSB=n
MK_USE_CRUSB_CDC=n
MK_CRUSB_IP=none

MK_USE_PX4_HRT=y
MK_USE_PX4_COMPONENT=n
MK_USE_PX4_UORB=n
MK_USE_PX4_WORKQUEUE=n

MK_USE_NET_LWIP_CORE=y
# app configuration
# PROJ_CDEFS += CONFIG_BOARD_FREERTOS_ENABLE
# PROJ_CDEFS += CONFIG_FR_MALLOC_FAILED_HANDLE
# PROJ_CDEFS += CONFIG_FR_IDLE_TIMER_TASKCREATE_HANDLE

# PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_ENABLE
# PROJ_CDEFS += CONFIG_CRUSB_CRUSB_CDC_ACM_STDOUT_BUFFER
# PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_STDINOUT
PROJ_CDEFS += CONFIG_BOARD_COM_STDINOUT
PROJ_CDEFS += CONFIG_BOARD_COM_STDOUT_DMA

PROJ_CDEFS += LWIP_ETHERNET_DEFAULT_IP=\"192.168.1.56\"
PROJ_CDEFS += LWIP_ETHERNET_DEFAULT_GATEWAY=\"192.168.1.1\"
PROJ_CDEFS += LWIP_ETHERNET_DEFAULT_MASK=\"255.255.255.0\"

PROJ_CDEFS += UP_UDP_IP=\"192.168.1.130\"
PROJ_CDEFS += UP_UDP_PORT=6001

# PROJ_CDEFS += UP_UDP_IP=\"192.168.75.128\"
# PROJ_CDEFS += UP_UDP_PORT=5001

PROJ_CINCDIRS += ${APP_PROJ_DIR}

CSOURCES += ${APP_PROJ_DIR}/ringbuffer.c

CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
CPPSOURCES += ${APP_PROJ_DIR}/gnss_pps_sync.cpp
CPPSOURCES += ${APP_PROJ_DIR}/rtcm_rcver.cpp
CPPSOURCES += ${APP_PROJ_DIR}/udp_echo.cpp
CPPSOURCES += ${APP_PROJ_DIR}/udp_transfer.cpp
CPPSOURCES += ${APP_PROJ_DIR}/canspeed_obd.cpp
CPPSOURCES += ${APP_PROJ_DIR}/sens_sync_proto.cpp

PROJ_CINCDIRS += apps/src/libs/rtklib
PROJ_CINCDIRS += apps/src/drivers/mpu6050
PROJ_CINCDIRS += apps/src/drivers/sch1633

CPPSOURCES += apps/src/libs/rtklib/rtcm3.cpp
CPPSOURCES += apps/src/libs/rtklib/rtcm3_st.cpp
CPPSOURCES += apps/src/libs/rtklib/rtkcmn.cpp
CPPSOURCES += apps/src/drivers/mpu6050/mpu6050.cpp
CPPSOURCES += apps/src/drivers/sch1633/sch1633.cpp
CPPSOURCES += apps/src/drivers/sch1633/sch1633_hw.cpp

