
PROJ_NAME  :=  lora_ota_master_bl
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/lorap2p_ota_sample/master_bl

CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=O1
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/stm32/stm32wle5_e77_900mbl/make.mk

# os and library config
MK_RTOS=none
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_POSIX=n
MK_USE_LIB_CPP=n

MK_USE_FS_FATFS=n
MK_USE_CRUSB=n
MK_USE_CRUSB_CDC=n
MK_CRUSB_IP=n

MK_USE_PX4_HRT=n
MK_USE_PX4_COMPONENT=n
MK_USE_PX4_UORB=n
MK_USE_PX4_WORKQUEUE=n

NVM_FLASH_BASE=0x0800b800
NVM_FLASH_SIZE=2K
BL_LOAD_CODE_BASE=0x08000000
BL_LOAD_CODE_SIZE=46K
BL_LOAD_ADDRESS=${BL_LOAD_CODE_BASE}

PROJ_SCF_DEFS += -DLR_CODE_BASE=${BL_LOAD_CODE_BASE}
PROJ_SCF_DEFS += -DLR_CODE_SIZE=${BL_LOAD_CODE_SIZE}
PROJ_SCF_DEFS += -DNVM_DATA_BASE=${NVM_FLASH_BASE}
PROJ_SCF_DEFS += -DNVM_DATA_SIZE=${NVM_FLASH_SIZE}

PROJ_CDEFS +=APP_LOAD_ADDRESS=${BL_LOAD_ADDRESS}

PROJ_CDEFS += CONFIG_BOARD_COM_STDINOUT
# PROJ_CDEFS += CONFIG_BOARD_COM_STDOUT_DMA

PROJ_CINCDIRS += ${APP_PROJ_DIR}
CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp


PROJ_CINCDIRS += ${APP_PROJ_DIR}/../
CPPSOURCES += ${APP_PROJ_DIR}/../nvm_board.cpp
