
PROJ_NAME  :=  usb_msc
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/usb_msc

# compile config
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1 #-flto
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LIB_USE_NANO:=y
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# os and library config
MK_RTOS=none
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_HARDFAULTINFO=y

MK_USE_MODULE_KPRINTF=y
MK_USE_KERNEL_CPP=n
MK_USE_KERNEL_POSIX_QUEUE=n
MK_USE_KERNEL_POSIX_MQUEUE=n
MK_USE_KERNEL_POSIX_PTHREAD=n
MK_USE_KERNEL_POSIX_SEMAPHORE=n
MK_USE_KERNEL_POSIX_TIMER=n
MK_USE_KERNEL_POSIX_TIME=n
MK_USE_KERNEL_WORKQUEUE=n
MK_USE_KERNEL_HRT=n
MK_USE_KERNEL_PERF=n

MK_USE_FS_FATFS=y
MK_USE_FS_LITTLEFS=n
MK_USE_FS_ROMFS=n
MK_USE_CRUSB=y
MK_USE_CRUSB_IP=dwc2_st
MK_USE_CRUSB_CLASS+=cdc_acm
MK_USE_CRUSB_CLASS+=msc
MK_USE_NET_LWIP_CORE=n

include ${SDK_ROOTDIR}/apps/board_selection.mk

PROJ_CDEFS += ${TEST_ITEM}
CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
