#include <board_config.h>
#include <drv_uart.h>
#include <drv_spi.h>
#include <drv_mmcsd.h>

#include <board_config.h>

// void DMA1_Stream6_IRQHandler()
// {
//     STM32_USART_DMA_TX_IRQ(2);
// }
// void DMA1_Stream5_IRQHandler()
// {
//     STM32_USART_DMA_RX_IRQ(2);
// }

// void DMA2_Stream3_IRQHandler()
// {
//     STM32_SPI_DMA_TX_IRQ(1);
// }
// void DMA2_Stream2_IRQHandler()
// {
//     STM32_SPI_DMA_RX_IRQ(1);
// }

// void DMA1_Stream4_IRQHandler()
// {
//     STM32_SPI_DMA_TX_IRQ(2);
// }
// void DMA1_Stream3_IRQHandler()
// {
//     STM32_SPI_DMA_RX_IRQ(2);
// }

void HAL_SD_MspInit(SD_HandleTypeDef *hsd)
{
/* SDMMC2
 *
 *      VDD 3.3
 *      GND
 *      SDMMC2_CK                           PD6
 *      SDMMC2_CMD                          PD7
 *      SDMMC2_D0                           PB14
 *      SDMMC2_D1                           PB15
 *      SDMMC2_D2                           PG11
 *      SDMMC2_D3                           PB4
 */

    LOW_PERIPH_INITPIN(GPIOD, 6,  IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_SDIO2);  
    LOW_PERIPH_INITPIN(GPIOD, 7,  IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_SDIO2);

    LOW_PERIPH_INITPIN(GPIOB, 14, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF9_SDIO2);
    LOW_PERIPH_INITPIN(GPIOB, 15, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF9_SDIO2);
    LOW_PERIPH_INITPIN(GPIOG, 11, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF10_SDIO2);
    LOW_PERIPH_INITPIN(GPIOB, 4,  IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF9_SDIO2);
}

#if defined(CONFIG_NET_LWIP_ENABLE)
void HAL_ETH_MspInit(ETH_HandleTypeDef* ethHandle)
{
    /* The STM32 H7 connects to a TI DP83848TSQ/NOPB
    * using RMII
    *
    *   STM32 H7 BOARD        DP83848TSQ/NOPB
    *   GPIO     SIGNAL       PIN NAME
    *   -------- ------------ -------------
    *   PA7     ETH_CRS_DV    CRS_DV
    *   PC1     ETH_MDC       MDC
    *   PA2     ETH_MDIO      MDIO
    *   PA1     ETH_REF_CL    X1
    *   PC4     ETH_RXD0      RX_D0
    *   PC5     ETH_RXD1      RX_D1
    *   PB11    ETH_TX_EN     TX_EN
    *   PG13    ETH_TXD0      TX_D0
    *   PG12    ETH_TXD1      TX_D1
    *
    * The PHY address is 1, since COL/PHYAD0 features a pull up.
    */

    // /** ETH_MDC, ETH_RXD0, ETH_RXD1 */
    // LOW_PERIPH_INITPIN(GPIOC, 1, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);
    // LOW_PERIPH_INITPIN(GPIOC, 4, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);
    // LOW_PERIPH_INITPIN(GPIOC, 5, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);

    // /** ETH_REF_CLK, ETH_MDIO, ETH_CRS_DV */
    // LOW_PERIPH_INITPIN(GPIOA, 1, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);
    // LOW_PERIPH_INITPIN(GPIOA, 2, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);
    // LOW_PERIPH_INITPIN(GPIOA, 7, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);

    // /** ETH_TX_EN */
    // LOW_PERIPH_INITPIN(GPIOB, 11, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);

    // /** ETH_TXD0, ETH_TXD1 */
    // LOW_PERIPH_INITPIN(GPIOG, 13, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);
    // LOW_PERIPH_INITPIN(GPIOG, 12, IOMODE_AFPP, IO_NOPULL, IO_SPEEDMAX, GPIO_AF11_ETH);

    LOW_PERIPH_INITPIN(GPIOC, 1, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
    LOW_PERIPH_INITPIN(GPIOC, 4, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
    LOW_PERIPH_INITPIN(GPIOC, 5, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);

    /** ETH_REF_CLK, ETH_MDIO, ETH_CRS_DV */
    LOW_PERIPH_INITPIN(GPIOA, 1, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
    LOW_PERIPH_INITPIN(GPIOA, 2, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
    LOW_PERIPH_INITPIN(GPIOA, 7, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);

    /** ETH_TX_EN */
    LOW_PERIPH_INITPIN(GPIOB, 11, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);

    /** ETH_TXD0, ETH_TXD1 */
    LOW_PERIPH_INITPIN(GPIOG, 13, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
    LOW_PERIPH_INITPIN(GPIOG, 12, IOMODE_AFPP, IO_PULLUP, IO_SPEEDMAX, GPIO_AF11_ETH);
}

void phy_reset()
{
    VDD_3V3_ETH_POWER_EN(false);
    board_delay(100);
    VDD_3V3_ETH_POWER_EN(true);
    board_delay(100); 
}
#endif
