
PROJ_NAME  :=  n32_test
PROJ_TC    :=  armcc
APP_PROJ_DIR = apps/test/boards_test/n32_test

# compile config
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1
CONFIG_LIB_USE_NANO:=y
CONFIG_C_STANDARD:=c11
CONFIG_CXX_STANDARD:=c++11
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/n32/n32g430_evk/make.mk

# os and library config
MK_RTOS=none
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_POSIX=n
MK_USE_LIB_CPP=n

MK_USE_FS_FATFS=n
MK_USE_CRUSB=n
MK_USE_CRUSB_CDC=n
MK_CRUSB_IP=none

MK_USE_PX4_HRT=n
MK_USE_PX4_COMPONENT=n
MK_USE_PX4_UORB=n
MK_USE_PX4_WORKQUEUE=n

# PROJ_SCF_DEFS += -DLR_CODE_BASE=0x08000000
# PROJ_SCF_DEFS += -DLR_CODE_SIZE=0x00200000

# app configuration
# PROJ_CDEFS += CONFIG_BOARD_FREERTOS_ENABLE

PROJ_CINCDIRS += ${APP_PROJ_DIR}
CSOURCES += ${APP_PROJ_DIR}/app_main.c

