
PROJ_NAME  :=  fankeh7_test
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/test/boards_test/fankeh7_test

# compile config
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1 #-flto
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LIB_USE_NANO:=y
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/stm32/fanke_tech_h7/make.mk

# os and library config
MK_RTOS=none
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_POSIX=n
MK_USE_LIB_CPP=n

MK_USE_FS_FATFS=y
MK_USE_FS_LITTLEFS=y
MK_USE_CRUSB=y
MK_USE_CRUSB_CDC=y
MK_CRUSB_IP=dwc2_st

MK_USE_PX4_HRT=y
MK_USE_PX4_COMPONENT=n
MK_USE_PX4_UORB=n
MK_USE_PX4_WORKQUEUE=n

PROJ_SCF_DEFS += -DLR_CODE_BASE=0x08020000
PROJ_SCF_DEFS += -DLR_CODE_SIZE=0x001e0000
PROJ_CDEFS += APP_LOAD_ADDRESS=0x08020000

# app configuration
# PROJ_CDEFS += CONFIG_BOARD_FREERTOS_ENABLE
# PROJ_CDEFS += CONFIG_FR_MALLOC_FAILED_HANDLE
# PROJ_CDEFS += CONFIG_FR_IDLE_TIMER_TASKCREATE_HANDLE

PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_ENABLE
PROJ_CDEFS += CONFIG_BOARD_STDINOUT=2

# PROJ_CDEFS += CONFIG_STM32_MMCSD_FATFS_SUPPORT
# PROJ_CDEFS += CONFIG_STM32_MTD_LFS_SUPPORT

PROJ_CINCDIRS += ${APP_PROJ_DIR}
CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp

