##
# Manufacturer Library files make Configuration
##

# for enable/disable low level driver user library
BSP_LIBCONFIG_STM32_LLDRV=y

# compile macros for low level driver user library
BSP_LIBCONFIG_STM32_LLDRV_SERIES=DRV_BSP_H7

# for sdk sources selection
BSP_LIBCONFIG_STM32_SERIES=BSP_STM32_H7

BSP_LIBCONFIG_STM32_HAL_USART=y
BSP_LIBCONFIG_STM32_HAL_IWDG=y
BSP_LIBCONFIG_STM32_HAL_RTC=y
BSP_LIBCONFIG_STM32_HAL_FLASH=n
BSP_LIBCONFIG_STM32_HAL_BASTIM=n
BSP_LIBCONFIG_STM32_HAL_I2C=y
BSP_LIBCONFIG_STM32_HAL_SPI=y
BSP_LIBCONFIG_STM32_HAL_QSPI=y
BSP_LIBCONFIG_STM32_HAL_MMCSD=y

include ${SDK_ROOTDIR}/bsp/stm32/libs/bsp_libs_stm32.mk

BOARD_CDEFS += STM32H743xx
BOARD_CDEFS += USE_HAL_DRIVER
BOARD_CDEFS += ${BSP_LIBCONFIG_STM32_LLDRV_SERIES}

BOARD_CSRCS += board_irq.c
BOARD_CSRCS += board_rcc_init.c
BOARD_CSRCS += board_usb.c
BOARD_CSRCS += board_init.c
BOARD_CSRCS += board_bsp.c

BOARD_ASMSOURCES += fmuv6_startup.s
BOARD_LNK_FILE   += fmuv6_lnk_script.ld

TMPBOARD_CSRCS = ${addprefix bsp/stm32/stm32h743_fmuv6/,${BOARD_CSRCS}}
TMPBOARD_ASMSOURCES = ${addprefix bsp/stm32/stm32h743_fmuv6/,${BOARD_ASMSOURCES}}
TMPBOARD_LNK_FILE = ${addprefix bsp/stm32/stm32h743_fmuv6/,${BOARD_LNK_FILE}}

BSP_BOARD_ENTRY_POINT :=  Reset_Handler

BSP_CDEFS += ${BOARD_CDEFS}

BSP_CSRCS += ${TMPBOARD_CSRCS} ${LIB_CSRCS}

BSP_CINCDIRS += bsp/stm32/stm32h743_fmuv6 ${LIB_CINCDIRS}

BSP_ASMSOURCES := ${TMPBOARD_ASMSOURCES}

BSP_LNK_FILE := ${TMPBOARD_LNK_FILE}

CONFIG_LINK_PRINTF_FLOAT:=y
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=O1



