
PROJ_NAME  :=  bl_ymodem
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/bl_ymodem

# compile config
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LIB_USE_NANO:=y
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/stm32/fanke_tech_h7/make.mk

# os and library config
MK_RTOS=frtos
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_POSIX=n
MK_USE_LIB_CPP=n

MK_USE_FS_FATFS=n
MK_USE_CRUSB=y
MK_USE_CRUSB_CDC=y
MK_CRUSB_IP=dwc2_st

MK_USE_PX4_HRT=y
MK_USE_PX4_COMPONENT=n
MK_USE_PX4_UORB=n
MK_USE_PX4_WORKQUEUE=n

PROJ_SCF_DEFS += -DLR_CODE_BASE=0x08000000
PROJ_SCF_DEFS += -DLR_CODE_SIZE=127K

PROJ_SCF_DEFS += -DNVM_DATA_BASE=0x0801FC00
PROJ_SCF_DEFS += -DNVM_DATA_SIZE=1K

# app configuration
# PROJ_CDEFS += CONFIG_BOARD_FREERTOS_ENABLE
# PROJ_CDEFS += CONFIG_FR_MALLOC_FAILED_HANDLE
# PROJ_CDEFS += CONFIG_FR_IDLE_TIMER_TASKCREATE_HANDLE

PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_ENABLE
PROJ_CDEFS += CONFIG_CRUSB_CRUSB_CDC_ACM_STDOUT_BUFFER
PROJ_CDEFS += CONFIG_BOARD_STDINOUT=1
PROJ_CDEFS += BOARD_USB_CDC1_RX_BUFFER_LEN=2048

PROJ_CINCDIRS += ${APP_PROJ_DIR}
CSOURCES += ${APP_PROJ_DIR}/app_main.c

PROJ_CINCDIRS += apps/src/libs/ymodem/
CSOURCES += apps/src/libs/ymodem/ymdm_cmn.c
CSOURCES += apps/src/libs/ymodem/ymdm_rcv.c
