
PROJ_NAME  :=  lora_p2p_wlxx
PROJ_TC    :=  gae

CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=O1

TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board configuration
MOD_ARCH = m4
include ${SDK_ROOTDIR}/boards/stm32/stm32wl55_nucleo_wl55jc/make.mk
#stm32wl55_nucleo_wl55jc
#stm32wle5_e77_900mbl

# os and library configuration
CONFIG_MK_CHIP_ARCH=${MOD_ARCH}
CONFIG_MK_COMPILER=gcc
CONFIG_MK_USE_FREERTOS=n
CONFIG_MK_USE_FRMEM_METHOD=4
CONFIG_MK_USE_FR_POSIX=n
CONFIG_MK_USE_FS_FATFS=n
CONFIG_MK_USE_LIB_CPP=n

CONFIG_MK_USE_CRUSB=n
CONFIG_MK_USE_CRUSB_CDC=n
CONFIG_MK_CRUSB_IP=none

CONFIG_MK_USE_PX4_TASKS=n
CONFIG_MK_USE_PX4_HRT=n
CONFIG_MK_USE_PX4_UORB=n
CONFIG_MK_USE_PX4_WORKQUEUE=n
CONFIG_MK_USE_PX4_LOG=n
CONFIG_MK_USE_PX4_MODULE=n
CONFIG_MK_USE_PX4_PERF_CNTER=n

include ${SDK_ROOTDIR}/sched/make.mk
include ${SDK_ROOTDIR}/mm/make.mk
include ${SDK_ROOTDIR}/libs/make.mk
include ${SDK_ROOTDIR}/include/make.mk
include ${SDK_ROOTDIR}/usb/make.mk
include ${SDK_ROOTDIR}/px4/make.mk
CSOURCES      += ${FR_CSOURCES}
CPPSOURCES    += ${FR_CPPSOURCES}
PROJ_CINCDIRS += ${FR_CINCDIRS}

#####################################
# app configuration
# macro list: 
# bsp: 
#     CONFIG_BOARD_COM_STDINOUT
#     CONFIG_BOARD_FREERTOS_ENABLE
#     CONFIG_BOARD_CRUSB_CDC_ACM_ENABLE
#     CONFIG_BOARD_MTD_QSPIFLASH_ENABLE
#     CONFIG_BOARD_MTD_QSPIFLASH_FATFS_SUPPORT
#     CONFIG_BOARD_MTD_QSPIFLASH_RAW_RW_TEST
#     CONFIG_BOARD_MMCSD_ENABLE
#     CONFIG_BOARD_MMCSD_FATFS_SUPPORT
#     CONFIG_BOARD_MMCSD_RAW_RW_TEST
#     CONFIG_BOARD_MMCSD_INFO_CHECK
# rtos:
#     CONFIG_FR_MALLOC_FAILED_HANDLE
#     CONFIG_FR_IDLE_TIMER_TASKCREATE_HANDLE
# usb:
#     CONFIG_CRUSB_CDC_TX_FIFO_ENABLE
#     CONFIG_BOARD_CRUSB_CDC_ACM_STDINOUT
#####################################
PROJ_CDEFS += CONFIG_BOARD_COM_STDINOUT

APP_PROJ_DIR = apps/demo/wlxx_lora_p2p

PROJ_CINCDIRS += ${APP_PROJ_DIR}
PROJ_CINCDIRS += ${APP_PROJ_DIR}/loraP2P/
PROJ_CINCDIRS += ${APP_PROJ_DIR}/rtklib/

CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
CPPSOURCES += ${APP_PROJ_DIR}/ringbuffer.cpp
CPPSOURCES += ${APP_PROJ_DIR}/p2p_proto.cpp
CPPSOURCES += ${APP_PROJ_DIR}/rand_lcg_series.cpp

CPPSOURCES += ${APP_PROJ_DIR}/rtklib/rtcm3.cpp
CPPSOURCES += ${APP_PROJ_DIR}/rtklib/rtkcmn.cpp
CPPSOURCES += ${APP_PROJ_DIR}/rtklib/rtk_basemsg.cpp

CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/region_EU868.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/region_US915.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_common.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_if.cpp

CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_state.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_linkfind.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_raw.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_rawack.cpp
CPPSOURCES += ${APP_PROJ_DIR}/loraP2P/p2p_rawack_fhss.cpp



