
PROJ_NAME  :=  fmu_gnss_ins_p
PROJ_TC    :=  gcc
APP_PROJ_DIR = apps/fmu_gnss_ins_p

BUILD_TYPE := lib

# compile config
BUILD_COMPILE_OPTIMIZE:=-O1 #-flto
BUILD_C_STANDARD:=gnu11
BUILD_CXX_STANDARD:=gnu++11
BUILD_LINK_PRINTF_FLOAT:=n
BUILD_LINK_SCANF_FLOAT:=n
BUILD_LIB_USE_NANO:=n

CONFIG_TEST=y
CONFIG_POSIXRUN_ENABLE=y
CONFIG_FREERTOS_ENABLE=n
CONFIG_RTTNANO_ENABLE=n
CONFIG_RTOS_COMPILER="none"
CONFIG_RTOS_MEM_METHOD=1
CONFIG_GMSH=n
CONFIG_FINSH=n

CONFIG_CMBACKTRACE=n
CONFIG_HRT=y
CONFIG_KPRINTF=n

CONFIG_LIBC_QUEUE=y
CONFIG_LIBC_MQUEUE=n
CONFIG_LIBC_PTHREAD=n
CONFIG_LIBC_SEMAPHORE=n
CONFIG_LIBC_SEMAPHORE_INHERIT=n
CONFIG_LIBC_TIMER=n
CONFIG_LIBC_TIME=n
CONFIG_LIBCPP=n
CONFIG_LIBC_VFS=n
CONFIG_PIPES=n

CONFIG_MODULE_BUILTIN=y
CONFIG_MODULE_READLINE=y
CONFIG_MODULE_NSHLIB=y
CONFIG_MODULE_PERF=y
CONFIG_MODULE_WORKQUEUE=y
CONFIG_MODULE_WQUEUE=y
CONFIG_ORB_USE_PUBLISHER_RULES=y

CONFIG_NSH_LIBRARY=1
CONFIG_NSH_PROMPT_STRING="nsh>\x20"
CONFIG_NSH_READLINE=1
CONFIG_NSH_LINELEN=128
CONFIG_NSH_QUOTE=1
CONFIG_NSH_CMDPARMS=1
CONFIG_NSH_MAXARGUMENTS=15
CONFIG_NSH_ARGCAT=1
CONFIG_NSH_NESTDEPTH=8
CONFIG_NSH_BUILTIN_APPS=1
CONFIG_LIBC_TMPDIR="/tmp"
CONFIG_NSH_VARS=1
CONFIG_NSH_FILEIOSIZE=512
CONFIG_NSH_INITSCRIPT="init.d/rcS"
CONFIG_NSH_RUNPWD="/home/miku/__workplace/gpmx/apps/fmu_gnss_ins_p/rcS"
CONFIG_NSH_CONSOLE=1
CONFIG_READLINE_ECHO=1
CONFIG_READLINE_MAX_BUILTINS=20

CONFIG_TEST_ENTRY:=$(if $(TEST_ENTRY),$(TEST_ENTRY),null_test_item)

