#ifndef __INCLUDE_SIGNAL_H
#define __INCLUDE_SIGNAL_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <stdint.h>
#include <time.h>

/************************************************************************
 * Pre-processor Definitions
 ************************************************************************/

#define SI_USER         0  /* Signal sent from kill, raise, or abort */
#define SI_QUEUE        1  /* Signal sent from sigqueue */
#define SI_TIMER        2  /* Signal is result of timer expiration */
#define SI_ASYNCIO      3  /* Signal is the result of asynch IO completion */
#define SI_MESGQ        4  /* Signal generated by arrival of a message on an */
                           /* empty message queue */

#define SIGEV_NONE      0  /* No asynchronous notification is delivered */
#define SIGEV_SIGNAL    1  /* Notify via signal,with an application-defined value */
#define SIGEV_THREAD    2  /* A notification function is called (3) */

#define SIGUSR1       1  /* User signal 1 */
#define SIGUSR2       2  /* User signal 2 */
#define SIGALRM       3  /* Default signal used with POSIX timers (used only */
                        /* no other signal is provided) */
#define SIGCHLD     4  /* Used by child threads to signal parent thread */
#define SIGPOLL     5  /* Sent when an asynchronous I/O event occurs */

#define SIGSTOP       6
#define SIGTSTP       7
#define SIGCONT       8
#define SIGKILL       9
#define SIGINT        10
#define SIGQUIT       11
#define SIGTERM       12
#define SIGPIPE       13
#define SIGHUP        14
#define SIGTTIN       15

#define SIGCONDTIMEDOUT 16  /* Used in the implementation of pthread_cond_timedwait */
#define SIGWORK     17  /* Used to wake up the work queue */

#define SIG_ERR         ((_sa_handler_t)-1)  /* And error occurred */
#define SIG_IGN         ((_sa_handler_t)0)   /* Ignore the signal */

#define SIG_DFL       ((_sa_handler_t)1)   /* Default signal action */
#define SIG_HOLD      ((_sa_handler_t)2)   /* Used only with sigset() */

/********************************************************************************
 * Public Type Definitions
 ********************************************************************************/

#ifndef __SIGSET_T_DEFINED
typedef uint32_t sigset_t;   /* Bit set of 32 signals */
#define __SIGSET_T_DEFINED 1
#endif

union sigval
{
    int   sival_int;       /* Integer value */
    void* sival_ptr;       /* Pointer value */
};

typedef void (*sigev_notify_function_t)(union sigval value);

struct __pthread_attr;
struct sigevent
{
    uint8_t      sigev_notify; /* Notification method: SIGEV_SIGNAL, SIGEV_NONE, or SIGEV_THREAD */
    uint8_t      sigev_signo;  /* Notification signal */
    union sigval sigev_value;  /* Data passed with notification */
    sigev_notify_function_t sigev_notify_function; /* Notification function */
    struct __pthread_attr *sigev_notify_attributes;   /* Notification attributes */
};

struct siginfo
{
  uint8_t      si_signo;     /* Identifies signal */
  uint8_t      si_code;      /* Source: SI_USER, SI_QUEUE, SI_TIMER, SI_ASYNCIO, or SI_MESGQ */
  uint8_t      si_errno;     /* Zero or errno value associated with signal */
  union sigval si_value;     /* Data passed with signal */
};

typedef struct siginfo siginfo_t;

typedef void (*_sa_handler_t)(int signo);

/********************************************************************************
 * Public Function Prototypes
 ********************************************************************************/

#ifdef __cplusplus
#define EXTERN extern "C"
extern "C"
{
#else
#define EXTERN extern
#endif

#undef EXTERN
#ifdef __cplusplus
}
#endif

#endif /* __INCLUDE_SIGNAL_H */
