
PROJ_NAME  :=  px4_workqueue_test
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/test/px4_test/workqueue_test

# compile config
CONFIG_LINK_PRINTF_FLOAT:=y
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LIB_USE_NANO:=y
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# board bsp config
include ${SDK_ROOTDIR}/boards/stm32/stm32h743_fanke/make.mk

# os and library config
MK_RTOS=frtos
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_POSIX=y
MK_USE_LIB_CPP=y

MK_USE_FS_FATFS=n
MK_USE_CRUSB=n
MK_USE_CRUSB_CDC=n
MK_CRUSB_IP=none

MK_USE_PX4_HRT=y
MK_USE_PX4_COMPONENT=y
MK_USE_PX4_UORB=y
MK_USE_PX4_WORKQUEUE=y

PROJ_SCF_DEFS += -DLR_CODE_BASE=0x08000000
PROJ_SCF_DEFS += -DLR_CODE_SIZE=2048K

# app configuration
PROJ_CDEFS += CONFIG_BOARD_FREERTOS_ENABLE
PROJ_CDEFS += CONFIG_FR_MALLOC_FAILED_HANDLE
PROJ_CDEFS += CONFIG_FR_IDLE_TIMER_TASKCREATE_HANDLE

# PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_ENABLE
# PROJ_CDEFS += CONFIG_CRUSB_CRUSB_CDC_ACM_STDOUT_BUFFER
# PROJ_CDEFS += CONFIG_BOARD_CRUSB_CDC_ACM_STDINOUT
PROJ_CDEFS += CONFIG_BOARD_COM_STDINOUT
# PROJ_CDEFS += CONFIG_BOARD_COM_STDOUT_DMA

PROJ_CINCDIRS += ${APP_PROJ_DIR}
CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
CPPSOURCES += ${APP_PROJ_DIR}/ScheduledWorkItemDemo.cpp


