
ifeq (${CONFIG_FS_GROMFS},y)
PROJ_CINCDIRS += ${GPMPATH}/fs/romfs/
CSOURCES += ${GPMPATH}/fs/romfs/gromfs.c
endif

ifeq (${CONFIG_FS_CROMFS},y)
CSOURCES += ${GPMPATH}/fs/romfs/fs_cromfs.c

FS_CROMFS_CSOURCES         := build/${PROJ_NAME}/gencromfs.c
FS_CROMFS_GENERATE_TOOLSRC := ${GPMPATHABS}/tools/gencromfs.c
FS_CROMFS_GENERATE_TOOLOBJ := ${GPMPATHABS}/tools/gencromfs

FS_CROMFS_TARGET_PATH     := ${SDK_ROOTDIR}/apps/${PROJ_NAME}/romfs
FS_CROMFS_GENERATE_OBJSRC := ${SDK_ROOTDIR}/${FS_CROMFS_CSOURCES}

USER_FILE_PREBUILD += ${FS_CROMFS_GENERATE_OBJSRC}
USER_FILE_PREBUILD += ${FS_CROMFS_GENERATE_TOOLOBJ}

${FS_CROMFS_GENERATE_TOOLOBJ}: ${FS_CROMFS_GENERATE_TOOLSRC}
	@gcc ${FS_CROMFS_GENERATE_TOOLSRC} -o $@

${FS_CROMFS_GENERATE_OBJSRC}: ${FS_CROMFS_TARGET_PATH} ${FS_CROMFS_GENERATE_TOOLOBJ}
	@${FS_CROMFS_GENERATE_TOOLOBJ} ${FS_CROMFS_TARGET_PATH} ${FS_CROMFS_GENERATE_OBJSRC}

CSOURCES += ${FS_CROMFS_CSOURCES}

endif
