
PROJ_NAME  :=  boards_test
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/boards_test

BUILD_TYPE := exe

# compile config
BUILD_COMPILE_OPTIMIZE:=-O1 #-flto
BUILD_C_STANDARD:=gnu11
BUILD_CXX_STANDARD:=gnu++11
BUILD_LINK_PRINTF_FLOAT:=n
BUILD_LINK_SCANF_FLOAT:=n
BUILD_LIB_USE_NANO:=y

CONFIG_TEST=y
CONFIG_POSIXRUN_ENABLE=n
CONFIG_FREERTOS_ENABLE=n
CONFIG_RTTNANO_ENABLE=y
CONFIG_RTOS_COMPILER="gcc"
CONFIG_RTOS_MEM_METHOD=4
CONFIG_GMSH=n
CONFIG_FINSH=y

CONFIG_CMBACKTRACE=n
CONFIG_HRT=y
CONFIG_KPRINTF=y

CONFIG_LIBC_QUEUE=y
CONFIG_LIBC_MQUEUE=y
CONFIG_LIBC_PTHREAD=y
CONFIG_LIBC_SEMAPHORE=y
CONFIG_LIBC_SEMAPHORE_INHERIT=y
CONFIG_LIBC_TIMER=y
CONFIG_LIBC_TIME=y
CONFIG_LIBCPP=y
CONFIG_LIBC_VFS=y
CONFIG_PIPES=y
CONFIG_DEV_FIFO_SIZE=80
CONFIG_DEV_PIPE_SIZE=80
CONFIG_DEV_PIPE_VFS_PATH="/dev/pipes"
CONFIG_MTD=y
CONFIG_LIBC_LZF=y

CONFIG_MODULE_BUILTIN=y
CONFIG_MODULE_READLINE=n
CONFIG_MODULE_NSHLIB=n
CONFIG_MODULE_PERF=y
CONFIG_MODULE_WORKQUEUE=y
CONFIG_MODULE_WQUEUE=y

CONFIG_FS_FATFS=y
CONFIG_FS_LITTLEFS=n
CONFIG_FS_CROMFS=y
CONFIG_FS_GROMFS=n

CONFIG_CRUSB_DEVICE_ENABLE=y
CONFIG_CRUSB_IP="dwc2_st"
CONFIG_CRUSB_DEVICE_CDC_ACM_ENABLE=y
CONFIG_CRUSB_DEVICE_MSC_ENABLE=n

CONFIG_TEST_ENTRY:=$(if $(TEST_ENTRY),$(TEST_ENTRY),null_test_item)

CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
