
PROJ_NAME  :=  boards_test
PROJ_TC    :=  gae
APP_PROJ_DIR = apps/boards_test

# compile config
CONFIG_LINK_PRINTF_FLOAT:=n
CONFIG_LINK_SCANF_FLOAT:=n
CONFIG_COMPILE_OPTIMIZE:=-O1 #-flto
CONFIG_C_STANDARD:=gnu11
CONFIG_CXX_STANDARD:=gnu++11
CONFIG_LIB_USE_NANO:=y
TARGET_POSTBUILD := ${TARGET_DEST_FILENAME_BIN}

# enbale all component unit test
MK_TEST_ENABLE:=y

# os and library config
MK_RTOS=frtos
MK_RTOS_PLATFORM=gcc
MK_RTOS_MEM_METHOD=4
MK_USE_HARDFAULTINFO=y

MK_USE_MODULE_KPRINTF=y
MK_USE_KERNEL_CPP=y
MK_USE_KERNEL_POSIX_QUEUE=y
MK_USE_KERNEL_POSIX_MQUEUE=y
MK_USE_KERNEL_POSIX_PTHREAD=y
MK_USE_KERNEL_POSIX_SEMAPHORE=y
MK_USE_KERNEL_POSIX_TIMER=y
MK_USE_KERNEL_POSIX_TIME=y
MK_USE_KERNEL_WORKQUEUE=y
MK_USE_KERNEL_HRT=y
MK_USE_KERNEL_PERF=y

MK_USE_FS_FATFS=y
MK_USE_FS_LITTLEFS=y
MK_USE_FS_ROMFS=y
MK_USE_NET_LWIP_CORE=n
MK_USE_CRUSB=y
MK_USE_CRUSB_IP=dwc2_st
MK_USE_CRUSB_CLASS+=cdc_acm
# MK_USE_CRUSB_CLASS+=msc

ifeq ($(TEST_ITEM),)
$(error Invalid empty TEST_ITEM)
endif

include ${SDK_ROOTDIR}/apps/board_selection.mk

PROJ_CDEFS += ${TEST_ITEM}
CPPSOURCES += ${APP_PROJ_DIR}/app_main.cpp
